Feature/wiser project auto deploy fow
happy-geeks/wiser-task-scheduler pull request #274
Opened 2024-12-31 12:57 UTC by MarkVanDijkHG

# Describe your changes

The WTS has been extended to support auto project deploy. It allows the whole deployment of a Wiser project:
- Set the website offline
- Merge a Wiser branch
- Publish Wiser commits
- Merge GitHub repository staging into main
- Set the website online

Optionally other WTS configurations can be paused to prevent issues, such as imports, before the deployment starts. This can be done at an alternative time to allow long tasks to be paused to ensure they are not still running when the actual deployment is executed.

## Type of change

Please check only ONE option.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How was this tested?

Tested the whole flow multiple times on a test project. All unhappy flows, everywhere the code stops the deployment early, have been tested.

# Checklist before requesting a review
- [x] I have reviewed and tested my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I selected `develop` as the base branch and not `main`, or the pull request is a hotfix that needs to be done directly on `main`
- [x] I double checked all my changes and they contain no temporary test code, no code that is commented out and no changes that are not part of this branch
- [ ] I added new unit tests for my changes if applicable

# Related pull requests

N/A

# Link to Asana ticket

https://app.asana.com/0/7257459017111/1208747317644039

2025-01-02 15:47 UTC, GilianJuice requested changes
Forgot to set status to `Request changes` before.

2025-01-06 15:01 UTC, MarkVanDijkHG commented on WiserTaskScheduler/WiserTaskScheduler/Core/Services/AutoProjectDeployService.cs
> +            lastBranchSettingsUpdateTimes[1] = branchSettings.ChangedOn;
I changed it to two separate fields.

2025-01-06 15:01 UTC, MarkVanDijkHG commented on WiserTaskScheduler/WiserTaskScheduler/Core/Services/AutoProjectDeployService.cs
> +        // If the time to pause or update is to far in the future we should stop and wait till a better moment. Once passed this point the provided settings are locked in.
I changed the second sentence.

2025-01-06 15:01 UTC, MarkVanDijkHG commented on WiserTaskScheduler/WiserTaskScheduler/Core/Services/AutoProjectDeployService.cs
> +        // Pause configurations/services that need to be paused before the deployment. Any errors are logged and notified about inside the method.
The second part has been removed. I had it there since all other paths have logging at the same level and here it was in the method itself. But it doesn't add a lot of value since it would be logical indeed that the errors will be handled inside.

2025-01-06 15:01 UTC, MarkVanDijkHG commented on WiserTaskScheduler/WiserTaskScheduler/Core/Services/AutoProjectDeployService.cs
> +        result.TemplateName = null;
I removed the code. The objects gets serialized and stored in the `wiser_branches_queue` table and I wanted to have the values from the template that was used removed to prevent confusion. But while writing a comment I figured it might actually be useful for debugging to see what template was used and the `is_template` column will be `0` anyways indicating it is not seen as a template,

2025-01-06 15:01 UTC, MarkVanDijkHG commented on WiserTaskScheduler/WiserTaskScheduler/Core/Services/AutoProjectDeployService.cs
> +                     VALUES (@name, @branchId, 'merge', @data, 'Wiser Task Scheduler', 0, 1);
No idea why I used `@`, I changed them to `?`.

2025-01-10 15:03 UTC, MarkVanDijkHG commented on WiserTaskScheduler/WiserTaskScheduler/Core/Services/AutoProjectDeployService.cs
> +        if (deployStartDatetime > gitHubAccessTokenExpires)
The access token is now checked if it will be at least valid for 30 minutes. It's expected the whole deploy flow will be finished in that time. With big branch merges it might take longer, but for now we would ensure most of the deployments.

2025-01-10 15:04 UTC, MarkVanDijkHG commented on WiserTaskScheduler/WiserTaskScheduler/Core/Services/AutoProjectDeployService.cs
> +    private async Task SetConfigurationsPauseStateAsync(List<int> configurationsToPause, IWiserDashboardService wiserDashboardService, List<Service> allServices, bool pause)
As discussed. These configurations are selected in a dropdown in the Wiser module based on the information in the database. This stores the IDs that are directly used here. There is no chance a typo can be made causing a configuration not to be found.

2025-01-10 15:04 UTC, MarkVanDijkHG commented on WiserTaskScheduler/WiserTaskScheduler/Core/Services/AutoProjectDeployService.cs
> +        if (dataTable.Rows.Count == 0 || dataTable.Rows[0]["data"] == DBNull.Value)
I changed the code.

2025-01-10 15:04 UTC, MarkVanDijkHG commented on WiserTaskScheduler/WiserTaskScheduler/Core/Services/AutoProjectDeployService.cs
> +                     INSERT INTO _{WiserTableNames.WiserHistory}_{backupTableSuffix} SELECT * FROM {WiserTableNames.WiserHistory};
The table got created and filled, so the code worked as expected. In the examples I used I can't find it either, I might have misread some of the examples and combined them. I changed them to the `LIKE` variant to keep the primary key.

2025-01-10 15:06 UTC, MarkVanDijkHG commented
I changed the several hard-coded strings as requested in the general comment. All of the separate comments have been changed and has been responded on. After the weekend I will look into improving the summaries in the code and create a ticket to potentially refactor the GitHub code to a separate service.

2025-01-15 07:20 UTC, MarkVanDijkHG commented
Comments for the summaries have been extended and the Asana ticket for potential refactor for the code for GitHub has been made. Due to other changes in the WTS the project has been rebased.

2025-01-16 09:08 UTC, GilianJuice commented on WiserTaskScheduler/WiserTaskScheduler/Core/Services/AutoProjectDeployService.cs
> +            if (workflowRuns == null || !workflowRuns.Any() || workflowRuns.All(wr => wr["status"].Value<string>() != "completed"))
I disagree with this, I don't expect that GitHub will add new properties every week, so having to keep a model up-to-date is a non-issue and I also see nothing wrong with only adding the properties that we need and adding more later when we need them.

The current way is much more confusing, now you don't have any way to see which properties are available, except for going to the GitHub documentation. If you make a model, even if you don't add all properties to it, you can at least add documentation to the properties so that people can see in the code what each property does, instead of having to open a browser to check.

Also, doesn't GitHub have an SDK for .NET? If so, we should use that, then we will have a model and we don't have to keep it up-to-date ourselves.

But anyways, since this is going to be refactored later anyways, we can save this for then.

2025-01-16 09:30 UTC, GilianJuice approved these changes

2025-01-16 09:30 UTC, merged