Refactor the implementation of Slack messaging.
happy-geeks/wiser-task-scheduler pull request #51
Opened 2023-02-22 16:21 UTC by MarkVanDijkHG

https://app.asana.com/0/7257459017111/1201816475294296

2023-02-24 09:00 UTC, HansJuice requested changes

2023-03-01 12:37 UTC, MarkVanDijkHG commented on WiserTaskScheduler/WiserTaskScheduler/Core/Services/LogService.cs
> +                        if (slackSettings != null && !string.IsNullOrWhiteSpace(slackSettings.BotToken) && !String.IsNullOrWhiteSpace(slackSettings.Channel) && logLevel >= logSettings.SlackLogLevel)
Dit is nu rechtgetrokken

2023-03-01 12:38 UTC, HansJuice approved these changes

2023-03-01 12:38 UTC, MarkVanDijkHG commented on WiserTaskScheduler/WiserTaskScheduler/Core/Services/LogService.cs
> +                                Channel=slackSettings.Channel
Dit is aangepast.

2023-03-01 12:38 UTC, merged